### ISSUE TITLE
ヒットアンドブローのルール

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#1]
- 0～9までの数字4桁を当てるゲーム
- 桁違いの一致は「ブロー」、桁まで一致したら「ヒット」としてカウントする
- 4ヒットでゲームクリア

よりProductの開発らしく、
Issueは出題者(仕様を握っているお客様仮定)からの要望で、マージされたらリリース、として見なしていく。

- 仕様に関する質問はここで。
- 実装に関する質問はそれ以外で。

**Comment by kitazawasyogo** [comment]
HitAndBlowゲームを作成する為、仕様について確認したい事がございます。
ルールに合わせ、以下のような機能を考えていますが修正点などありましたらご指摘頂けたらと思います。

①コンソールで入出力を行う
②ヒット数とブロー数を表示しもう一度入力を求める
③4ヒットしてゲームクリアするまで繰り返しチャレンジできる
④4桁の数字以外が入力された場合はメッセージを表示する
⑤クリア出来たらもう一度遊べるか辞めるか選ぶ

**Comment by kitazawasyogo** [comment]
@nabemasamasa　@Takatatsu9
メンション忘れてしまったのでメンションさせて頂きます。

仕様についての質問です。
お忙しいところ恐れ入りますが回答お願い致します。

**Comment by Takatatsu9** [comment]
「仕様は自分が考えたから間違ってたら教えて」ってなんかおかしくないですか？
issueに書いてますよね、「出題者(**仕様を握っているお客様**仮定)からの要望」って。
ある程度具体性のある仕様なら肉付けして確認するのはいいんですけど、
仕様が無いとか曖昧な仕様は自分で勝手に作らないほうがいいです。

**Comment by kitazawasyogo** [comment]
〇〇な場合の仕様はどうしますか？
という形で確認するようにします。

**Comment by kitazawasyogo** [comment]
HitAndBlowゲームを作成する為、仕様について確認したい事がございます。

①入出力は何で行うか
②ゲームクリアではない場合の動作　例：ヒット数、ブロー数を表示してもう一度入力を求める、クリア迄繰り返しチェレンジ出来る。など
③4桁の数字以外が入力された場合
④クリアした後の動作　例：即終了、キー入力を指示して終了、もう一度遊ぶか終了するか選択できる。など

以上、よろしくお願いいたします。

**Comment by nabemasamasa** [comment]
コンソールアプリを想定しています。
クリアするまでは、適宜ヒット数とブロー数を表示して、もう一度入力を求めてください。
想定しない入力があった場合、その旨表示して、もう一度入力を求めてください。
クリアした後は、「もう一度遊びますか？(Y/N)」を表示して、Yだったらもう一度遊べるようにし、Nだったらアプリケーションを終了させてください。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

文言などの指定はありますでしょうか。もしくはこちらで決めてしまってよろしいでしょうか。

表示する事が想定できるメッセージ等
①正解の4桁の数字
②ゲーム開始時入力をする指示メッセージ
③ヒット数、ブロー数の表示
④想定していない入力の場合に表示するメッセージ
　・例「4桁の数字を入力してください」で統一する場合
　・例「桁数が違います」など想定外の内容ごとにメッセージを分ける場合

**Comment by nabemasamasa** [comment]
① 「正解の4桁の数字」とは何のことでしょうか？

②は数値の入力を求めることがわかるのであれば、自由に表示してくださって構いません。
③は`(ヒット数)ヒット　(ブロー数)ブロー`もしくは`ヒット：(ヒット数)  ブロー：(ブロー数)`のどちらかでお願いします。
④は数値以外が入力されている事がわかれば、自由に表示してくださって構いません。

**Comment by kitazawasyogo** [comment]
①「正解の4桁の数字」は、入力値と比較する値です。

比較する値は毎回同じ値ではなく、ゲームごとに毎回変える仕様でしょうか？

**Comment by nabemasamasa** [comment]
> 表示する事が想定できるメッセージ等

すぐ上にこの1文がありました。なので、ユーザーに表示させるメッセージの仕様についてだと思ったのですが、、、、。

[Q] マインスイーパやソリティア、麻雀とかのアプリでも「もう一度遊ぶ」時は同じセットで遊ぶんですか？

**Comment by kitazawasyogo** [comment]
> すぐ上にこの1文がありました。なので、ユーザーに表示させるメッセージの仕様についてだと思ったのですが、、、、。

書き方が悪く混乱させてしまい申し訳ありません。

毎回リセットされます。
HitAndBlowも「もう一度遊ぶ」時に新しい比較する値が設定されるようにします。

**Comment by kitazawasyogo** [comment]
お忙しい中回答ありがとうございました。

仕様について質問したい内容は以上です。

**Comment by kitazawasyogo** [comment]
仕様について追加で確認したいことがございます。

正解の値（4桁の数字）と入力値（4桁の数字）はそれぞれ同じ数字が設定される事を許す仕様でしょうか？
例：正解の値（1313）　入力値（1133）ヒット数2　ブロー数2
例：正解の値（1378）　入力値（1111）ヒット数1　ブロー数3
例：正解の値（1111）　入力値（2451）ヒット数1　ブロー数3

**Comment by nabemasamasa** [comment]
正解の値は **重複しない** 4桁の数字にしてください。
入力値については、同じ数字を許可していいです。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
