### ISSUE TITLE
正解まで何手かかったか表示する機能が欲しい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#10]
ゲームを開始してから、クリアするまで何回数字を入力したか表示してほしいです。

**Comment by kitazawasyogo** [comment]
正解まで何手かかったか表示する機能を追加する為に仕様について質問させて頂きます。

〇表示する文言について
以下の文言で表示させるイメージでよろしいでしょうか？
例：4桁の数字を入力してください：1234
　　ヒット数：4！ゲームクリア！
　　ゲームクリアまでは8手かかりました。
　　もう一度遊びますか？（Y/N）：

**Comment by nabemasamasa** [comment]
(「質問させていただきます」なのに、質問する形になってない……。聞き方にサンプルがあってとてもいいのに、惜しい……。)

「以下の文言で表示させるイメージでよろしいでしょうか？」ということでしょうか？
とても良いと思います。是非、これでお願いします。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
仕様に合わせて機能追加行います。

仕様について質問したコメント編集させて頂きます。

**Comment by kitazawasyogo** [comment]
「質問させていただきます」とコメントしましたが、質問する形になっていませんでした。
失礼いたしました。
ミスの対応として既に仕様確認としてコメントした内容を修正してしまったことも不適切でした。
今後同じことが無いよう改めさせて頂きます。
