### ISSUE TITLE
挑戦桁数を変更できるようにしてほしい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#11]
ゲーム開始時に、3ケタから10ケタまで、挑戦者が挑戦できる桁数を選べるようにしてほしいです

**Comment by kitazawasyogo** [comment]
挑戦桁数を変更できるようにする機能の仕様について確認したいことがございます。

①挑戦桁数を選ぶ時に表示す文言について指定はございますか？
②想定外の入力があった場合の挙動について
　例：入力値が想定外であることを伝えるメッセージを表示して再入力を求める。
③想定外の入力があった場合に表示する文言について指定はございますか？
　例：入力値が想定内の桁数の値ではありません。
④以前のゲームの挑戦桁数はリセットされ毎ゲーム桁数を選択して遊ぶという認識で正しいでしょうか。

**Comment by nabemasamasa** [comment]
① 特に指定はありません。ユーザーに分かれば良いです。
② 想定外の入力があった場合は、再入力を求めてください。
　桁数の指定がないのにゲームを始められないと思うので。
③ 例のパターンだと固いので、もう少しシンプルだと良いです。
　- 例a: 数値以外の場合、「数字以外が入力されています」
　- 例b: 3未満、11以上の場合は「範囲外です」など
④ 桁数を変えるか確認し、入力次第でその桁数のまま続行するか、再度確認するか選べるようにしてほしいです。
     再度確認する場合は、①のメッセージをまた表示してください。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
仕様に合わせて機能追加行います。
