### ISSUE TITLE
クリア後の「もう一度遊びますか？(Y/N)：」でY/Nの小文字の許容について

### ISSUE THREAD

**Issue by kitazawasyogo** [kitazawasyogo/HitAndBlow#15]
仕様について考慮漏れがあり、Issueにて追加で質問させていただきます。

クリア後の「もう一度遊びますか？(Y/N)：」で大文字の（Y/N）以外に、小文字の（y/n）が入力された場合についてどのような仕様をお考えでしょうか？

**Comment by nabemasamasa** [comment]
(お客様として回答するなら……)
仕様については考えていませんでした。
許容してください。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

クリア後にもう一度遊ぶかの入力を求めた時に、（YとN）大文字、小文字どちらを入力しても許容されるように変更いたします。
