### ISSUE TITLE
クリアまでにかかった時間を表示してほしい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#18]
ゲームを開始してから、クリアするまでの時間を表示してほしいです

**Comment by kitazawasyogo** [comment]
ゲーム開始からクリアするまでの時間を表示する機能の仕様について確認したいことがございます。

①表示する内容について
（1）どの単位まで表示するのか（時間、分、秒...）
（2）50秒でクリアした場合は、時間と分の表示を行いますか？
（3）08分と表示するのか、8分と表示するか
②表示する文言について指定はございますか？
　例：ゲームクリアまでは8手かかりました。
　　　ゲームクリアまでは01時間15分09秒かかりました。
　　　もう一度遊びますか？(Y/N)：
③時間の計測開始と終了のタイミングについて
　例：（開始：挑戦桁数を入力or挑戦桁数変更しない場合の後、「n桁の数字を入力して下さい：」のメッセージが表示された後）
　　　（終了：全てヒットの値の入力が行われた後）

**Comment by nabemasamasa** [comment]
- ①
  - (1) 分と秒とミリ秒でお願いします。
  - (2) 秒だけで収まる場合は、分の表示は行わないでください。
  - (3) 0埋めでお願いします。
- ② 提示していただいた例だと冗長ですので、手数と時間は1行でお願いします。
     - `ゲームクリアまでXX手、mm分ss.sss秒かかりました。`
- ③ 記入途中のように見えましたが、、、、「以下でよろしいでしょうか？」という事でしょうか、、、？

(末尾、「するのか」「ますか？」「するか」「について\n   例:…」など、一貫性がないです。コメント投稿前の見直ししてほしいです)

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

③その通りです。
　　時間の計測開始と終了のタイミングについて以下でよろしいでしょうか？
　　開始：挑戦桁数を入力or挑戦桁数変更しない場合の後、「8桁の数字を入力して下さい：」のメッセージが表示された後
　　終了：全てヒットの値の入力が行われた後

末尾に一貫性がありませんでした。
失礼いたしました。
今後同じことが無いよう改めさせて頂きます。

**Comment by nabemasamasa** [comment]
ありがとうございます。
実際に正解を当てる為の入力を求めるメッセージを表示してから、ゲームクリアのメッセージを表示する直前までとさせてください。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
仕様に合わせて機能追加行います。
