### ISSUE TITLE
答えを見る隠し機能がほしい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#4]
`ShowAnswer`と入力したら、答えを表示する

**Comment by kitazawasyogo** [comment]
仕様についてご質問させていただきます。

①ゲームを遊ぶ人は`ShowAnswer`と入力すれば答えが見られるという事を知らないかと思いますが、コンソールに出力して知らせるタイミングはいつでしょうか？隠し機能という事は、知らせないのでしょうか。
②表示する文言の指定について
・ShowAnswerと入力すれば答えを見れる事を知らせる時
・答えを表示する時

**Comment by nabemasamasa** [comment]
①: お察しの通り、隠し機能なので表示しないようにお願いします。
②-1:  ①で回答させていただいた通り、表示しないので指定はございません。
②-2: 答えの数字だけの行で表示させてください。

**Comment by kitazawasyogo** [comment]
追加で仕様について確認したいことがございます。

`ShowAnswer`という入力ですが、大文字と小文字の判定についてはどのような仕様をお考えでしょうか。

**Comment by nabemasamasa** [comment]
大文字と小文字の判定、とはどういうことでしょうか？
区別するか？ということでしょうか？
もしそうだとしたら、隠し機能なので決め打ちが望ましいです。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

その通りです。
大文字と小文字で区別しますか。という質問です。

`ShowAnswer`と入力された場合だけ答えを表示し、`Showanswer`や`showanswer`は想定外の入力値として再入力を求めるように致します。
