### ISSUE TITLE
[バグ？] 配布されたHitAndBlow.exeを実際にプレイしてクリア後、Nを押してもアプリが閉じない

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#5]
リリースとして展開されたExeをキックし
![image](https://user-images.githubusercontent.com/20126608/217965772-5aacd6fa-9879-4739-a395-5c3d852c2222.png)
立ち上がったアプリを実行し、クリア後もう一度プレイするか聞かれたのでNを押すが、押してもすぐに閉じない。
![image](https://user-images.githubusercontent.com/20126608/217966194-744870b0-70dc-481c-b322-0cbbc58249c8.png)

**Comment by nabemasamasa** [comment]
あと、「N」を押した後、「ESC」キーを押すと「N」を入力したはずなのにもう一度プレイさせられてしまう

**Comment by kitazawasyogo** [comment]
「N」を押してもすぐに閉じないという事は、「N」を入力し、Enterキーを押しても直ぐに閉じないという事でしょうか？

**Comment by nabemasamasa** [comment]
「N」を入力した後、「Enter」キーを押す事で閉じることが出来ました。
以前提示した仕様だと、「N」でアプリケーションを終了させるようにお願いしていたと思ったのですが、
何か条件があるのでしょうか？
https://github.com/kitazawasyogo/HitAndBlow/issues/1#issuecomment-1409661582

**Comment by kitazawasyogo** [comment]
直ぐに閉じなかったのは、コンソール画面がすぐに閉じないようになる不要な処理があった為だと思います。

他のIssueで「もう一度遊ぶか最後に選択する」機能の修正を行いリリースしましたが、その際にこちらのIssueで問題となっているすぐにアプリが閉じないという問題も解決されたと考えています。

最新のリリースされているHitAndBlowゲームでもこちらのIssueで問題となっている個所は想定している仕様通りの挙動になっていないでしょうか。

**Comment by kitazawasyogo** [comment]
別のIssueで「ゲームクリア後にもう一度遊ぶか辞めるか選択する」機能の修正を行いリリースしましたが、こちらのIssueで問題となっている「すぐにアプリが閉じない」という問題も解決されていると思います。

最新のリリースされているHitAndBlowゲームでもこちらのIssueで問題となっている箇所は想定している仕様通りの挙動になっていないでしょうか。

解決済みでしたらこちらのIssueはCloseさせて頂きたい思います。

**Comment by nabemasamasa** [comment]
ありがとうございます。
最新リリースで修正されていることを確認しました。
Closeします。
