### ISSUE TITLE
クリア後の「もう一度遊びますか？(Y/N)：」でY/N以外の値が入力された場合、再入力させてほしい

### ISSUE THREAD

**Issue by kitazawasyogo** [kitazawasyogo/HitAndBlow#8]
仕様についての確認漏れがあり、Issueを立てて追加で質問させていただきます。

クリア後の「もう一度遊びますか？(Y/N)：」でY/N以外の値が入力された場合の仕様についてですが、どのような仕様をお考えでしょうか？

例：もう一度再入力を求めるなど

**Comment by Takatatsu9** [comment]
これ #5 に関係する話ですか？

**Comment by kitazawasyogo** [comment]
#1 での確認漏れです。

https://github.com/kitazawasyogo/HitAndBlow/pull/7#discussion_r1102158460
（こちらの頂いたコメントの対応を行う為の仕様確認です。）

**Comment by nabemasamasa** [comment]
@Takatatsu9 「『N』を押してもアプリが閉じない」のと「Y/N以外を押すと問答無用でもう一度プレイさせる」のはまた別の話かな…。どちらも同じ機能の話ではあるけど。

@kitazawasyogo 
提案通り、何もせずに再入力を求めてほしいです。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。

それでは、Y/N以外の入力が行われた場合は再入力を求めるようにします。
①-1入力内容が違うことをコンソールに表示するかについて
①-2入力内容が違うことを表示する場合の文言の指定について
②再入力を求める際の文言などに指定はございますか？

例　もう一度遊びますか？(Y/N)：M
　　入力内容が異なります。
　　もう一度遊びますか？(Y/N)：
　　
例　もう一度遊びますか？(Y/N)：MMMMM
　　もう一度遊びますか？(Y/N)：

**Comment by nabemasamasa** [comment]
上の例でお願いします。
