### ISSUE TITLE
ギブアップ機能がほしい

### ISSUE THREAD

**Issue by nabemasamasa** [kitazawasyogo/HitAndBlow#9]
`giveup`と入力されたら、答えを表示してゲームを終了させてください。

**Comment by kitazawasyogo** [comment]
ギブアップ機能の機能追加にを行う為に仕様について質問させて頂きます。

①「giveup」の大文字、小文字の許容について
②答えを表示した後、ゲーム終了の挙動について
　例1.「もう一度遊びますか？(Y/N)：」でNを入力した場合と同じ挙動
　例2.一ゲーム目は終了で、「もう一度遊びますか？(Y/N)：」と表示する

②答えを表示し終了する際の文言
　例：4桁の数字を入力して下さい：giveup
　       1234
　       ゲーム終了です。
　       もう一度遊びますか？(Y/N)：

**Comment by nabemasamasa** [comment]
①大文字や小文字の違いは許容して構いません。
②答えを表示した後、もう一度遊ぶか確認をお願いします。
③正解の数字だったことをわかるよう、数字の前に「ゲームらしい」一言をお願いします。

**Comment by kitazawasyogo** [comment]
回答ありがとうございます。
仕様に合わせて機能追加行います。
